name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-on-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.13
      - name: Build examples
        run: |
          mkdir build
          pushd build
          cmake ..
          make -j$(nproc)
          popd
      - name: Run tests
        run: |
          python3 ./test/test.py
