name: test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-on-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.13
      - name: Pull submodules
        run: |
          git submodule update --init --recursive
      - name: Format check
        uses: DoozyX/clang-format-lint-action@v0.15
        with:
          source: 'include examples'
          extensions: 'c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx,i,ixx,ipp,i++'
          clangFormatVersion: 14
          inplace: False
      - name: Build examples
        run: |
          mkdir build
          pushd build
          cmake ..
          make -j$(nproc)
          popd
      - name: Run tests
        run: |
          python3 ./test/test.py

  test-on-windows:
      runs-on: windows-latest
      steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
      - name: Pull submodules
        run: |
          git submodule update --init --recursive
      - name: Build examples
        run: |
          mkdir build
          pushd build
          cmake ..
          MSBuild "simple_logger.sln" "-t:Build" "-p:Configuration=Release;Platform=x64" "-m"
          popd
      - name: Run tests
        run: |
          python3 ./test/test.py
